# Generated by Django 4.1.5 on 2023-08-10 07:58

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('descriotion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='videoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='videoAndCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.catagory')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.videoinfo')),
            ],
        ),
    ]
